server:
  port: ${PORT:8090}

spring:
  application:
    name: user-service

  r2dbc:
    url: r2dbc:postgresql://ep-curly-grass-a8caygw5-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_qbQcf7v0xmPn
    pool:
      enabled: true
      max-size: 10
      initial-size: 2
      max-idle-time: 30s

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  codec:
    max-in-memory-size: 10MB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/prs2-83d22
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com

  feign:
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000
          loggerLevel: BASIC

firebase:
  credentials: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAicHJzMi04M2QyMiIsCiAgInByaXZhdGVfa2V5X2lkIjogImU5MTE5OTZjNjVkOWY0MmU1YjMxZDI2ZWYyNGQ0YTUzYWI0MDBjYTciLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRREF0cXRRdit0RXpYLytcbmhjRGhqMWlqbWxNdnpVeXc0UG44dGxXN3RQeU1aWUJQRXJUYkxBOWZHeUFRbU45bVZHcUwzWWVlR2Y3eTRKaXFcbityMUpEMjBMNlJYbE5RcDA1b1g5VVJUNFBYcDNTWnpnU3JlMFFjdmhzVElJVXkxYnRCTzE4U1BLUkRtdnE3SUNcblZnSmRSZnlGb2pOSHl6UnNiQWRmcnpiSUZTR2RHRzh4QldabmZFeUpOckFQd0E2a3I2VVdHWE9mSURzUmV4djBcbjlOQnphQ0VYeW1JTkFDNUFieUZya2YrLzI4WnNRWE8yV1o3TWNKK3JjUm5iMlc2OTk1L2V5RVNSQUV1dUlxUmFcblpyY1pYV3VMTnAzWXZvRUkxQk9LTkRiY2hmWm40ZzVQaTh1VVdYRld2cmQraVFublpVUTFxYi9CcTdVcGNUMUZcbnA3aGsydEtUQWdNQkFBRUNnZ0VBU29FVXdIWkNSZXBROXB6TlVpYnlOT1lBRFRZSTFVVlZRSTlabStVLzBpT1hcbnRIcGQ4M0lZUzBPWVpQSkZSREdVczVna3kwbnZtQVNlNFZOcEJLcnpGS3k3YTA3VFNSaXFhcUlEUW1tNlJBM3dcbm1ZSXBmWVlHaGEzVTB3VWRQeHZpbHUrd1Q0Mks0OUMwVkZUZU95TkltbjEzNStTMjBzZjlIZEFHbE5vZWtiWG9cblkrL3A3UFErMGxZb3dyQmRPR2Z6T3JGb3dSK1MwM3JBd3B4SlVaU1pnUjVWNzBxSUtGZklrVnh4VUJ3N3crUXBcbkh2VFVQTVF4bUtJSVJTK0dUT3Z0VC9qSXBqbHRSaDdrN0tJVi9zaklzSUlTVjNoc1kzZHd2Yk9Mak16VTZuR21cbjY1bE5nbEFYSU5mTmYxR0NQcWFpeVplUHIxREtjSzY4ZTVUK0pzbHFrUUtCZ1FEOVU3VkxXWGNXSDQvQnZVd0ZcbkIwWDl0bVhNYlpBdVdSNEZkNG5CTzV1U29TbXllSVpjZG9nNUk1QzJuL0tlelF1YlJOWnl3UkpSSUx1SHE0bXpcbkRZVlh6TTI3dCsyWEZDMmZ4UTYvbVRNRThKT2lXUlRiQ3FDbWVWNEtpdUg5L2VybmFLbnVtUU5QTWkybktrbS9cbjArRWlBSWYrRmFnSURLazkvWGxENDhqYXFRS0JnUURDdnpzWFZvRFlUTTVRaUZYb3NGMmZ0V3A4cVV5dGxRNGFcbm9Qa1cyNWV6NFcvRFFYK3MxeURpUko3QnRUcTBMTFJuMDBSbEtrL2RaQ0JvM0tvR29uMml4ZWY2U3hmOEZ5R2lcbnhmUHhZNS9uT1BTY3ozd3V4NEsvdHFNWWl0TDhlUTRGOWdGaXozMXhXM2l1REZhaU1Kc3ZvaGtMVkhNMFZqLzNcbjBuZW1WQWdrMndLQmdBejkyd0ZYUUQwNU55VW5jUnVjNk9EL0ZxOXFPd2UxZUUydGVMb1pOWHhLbVpuV2hvVjlcbmFyVUxkdU4yeG5tUWFIVDVEY3Bxem1hc3VCRllJY0syQWMyajZqVWpWS0wzM1BNaHB3VDZkVnhlZmlQSVQ4S0FcbkJBY2xtRVlRSTFEa1VjUzJZR2lsSGo5VWduVGRQVlVDSjd5WHJHSENlSkNaSGFEWk8vdllWYmVwQW9HQkFKakdcbkU4RVhKelNIN0VIWThpdjhUelgreDI3TUVVOEs0Mm1ZWmsrOExLSDhkQVNrMlZmcDIrNGxEclcvU2pJVjcrQ1Rcbko5Q0ZCT29VcGlnZEUzVG8rODQ1bXVZTEN1SEQ4NnNSeDNEU1NwckZYMyswZFNMdGVIQ1ZBaFU2c3BGRkZlOHZcbk1aOG1UcTRpcCtWQjRLU1RwT29WSzdocm80U25OTDlnNkdRZS85U0pBb0dCQUxYdWltVExLcTVhcVQzKzhITkhcblFvckNUOVQweXBvNTBZdjVyVkJaRTJIc2hLMWcrc29CSituNXRGL2pvdUtBUVc0d1RTeFJQdWN2TWVySUtEaFZcbmRxaWFiMXJmQmJaN3lkM2VWZW84amxEeTV5U3d3VHduTWJsbEZDRkdLbE9MTzVFcUplNjdxMXIxQU9keWlqeDVcbjVTOFdoRGhOYWRMSDhkWHlXOFh3R2pXZFxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogImZpcmViYXNlLWFkbWluc2RrLWZic3ZjQHByczItODNkMjIuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTAxNjY2MjE2NzY3NDYwODA2Njg3IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9maXJlYmFzZS1hZG1pbnNkay1mYnN2YyU0MHByczItODNkMjIuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0K


logging:
  level:
    pe.edu.vallegrande.user_service: DEBUG
    io.r2dbc: DEBUG
    org.springframework.web.cors: DEBUG
    org.springframework.security.web.server: DEBUG
